server:
  port: 8083

spring:
  datasource:
    name: test
    url: jdbc:mysql://198.12.71.159:3306/msq
    username: msq
    password: Nhm4J2jkMMFsCEPD
    driver-class-name: com.mysql.cj.jdbc.Driver
  devtools:
    restart:
      enabled: true
      additional-paths: src/main/java

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.test.bean

